### ISSUE TITLE
Add librewolf as an option from web browser or just default.

### ISSUE THREAD

**Issue by zqpvr** [daechir/xenos-install-kit#2]
It is a hardened version of Firefox https://librewolf.net

**Comment by daechir** [comment]
Hi,

Personally I don't see an issue adding it as an option but certainly not as a replacement. Madaidan does a fantastic job comparing chromium vs firefox security [here](https://madaidans-insecurities.github.io/firefox-chromium.html) . In short, I can make it so you can pick which one(s) you want by writing to variables in S2b.sh. If you have any thoughts let me know.

**Comment by daechir** [comment]
Summarizing this issue:
Add additional options for web browsers

Solution:
See commit [v3g6](https://github.com/daechir/xenos-install-kit/commit/b5f1ff7a18cd0bb32d1653498345dfd65ee58be1)

Verified by:
Testing within the shell.
