### ISSUE TITLE
Name is not working when I reinstalled the system.

### ISSUE THREAD

**Issue by zqpvr** [daechir/xenos-install-kit#6]
LUKS password works now but name isn't working.

**Comment by daechir** [comment]
Summarizing this issue:
Duplicate of [issue #1](https://github.com/daechir/xenos-install-kit/issues/1)

Solution:
See commit [v3h1](https://github.com/daechir/xenos-install-kit/commit/471bec90f9649acef0b729064e12f45ddef3bc3a).

Verified by:
Testing and comparing variable output in the shell.
